# Generated by Django 4.2.2 on 2023-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_about_facebook_username_about_github_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
