# Generated by Django 4.2.2 on 2023-07-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_experience_company_site_alter_experience_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
