# Generated by Django 4.2.2 on 2023-07-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_education_school_site_alter_education_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='associated_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_associated_with', to='profile_page.experience'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fk_master_data_topic2', to='profile_page.masterdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fk_master_data_topic3', to='profile_page.masterdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
