# Generated by Django 4.2.3 on 2025-06-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_alter_award_updated_at_alter_masterdata_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterData',
            new_name='ProjectCategory',
        ),
    ]
