# Generated by Django 4.2.3 on 2025-06-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile_page', '0008_about_deleted_at_about_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='associated_with',
        ),
        migrations.CreateModel(
            name='ProjectAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='profile_page.project')),
            ],
            options={
                'unique_together': {('project', 'content_type', 'object_id')},
            },
        ),
    ]
