# Generated by Django 4.2.3 on 2025-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_remove_project_associated_with_projectassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='associated_with_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='associated_with_type',
            field=models.CharField(blank=True, choices=[('experience', 'Experience'), ('education', 'Education')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectAssociation',
        ),
    ]
