# Generated by Django 4.2.3 on 2025-06-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0011_award_associated_with_id_award_associated_with_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if this is current'),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, help_text='School location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_logo',
            field=models.URLField(blank=True, help_text='URL to school logo image', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.URLField(blank=True, help_text='URL to company logo image', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if this is current'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, help_text="Job location (e.g., 'Remote', 'New York, NY')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
