# Generated by Django 4.2.3 on 2025-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0012_education_is_current_education_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if this is current'),
        ),
    ]
